package vector

import (
	"context"
	"sort"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// Test the RRF helper in isolation. Fusion is the heart of
// the hybrid path; getting it wrong silently degrades search
// quality, so we pin its behavior here.

// Identical rankings from both sides → fused score is twice
// the single-side score for every document.
func TestRRF_IdenticalRankings(t *testing.T) {
	t.Parallel()

	semantic := []string{"a", "b", "c"}
	keyword := []string{"a", "b", "c"}
	got := rrfFuse(semantic, keyword, 60)

	require.Len(t, got, 3)
	// a ranks #1 in both → highest fused score.
	scores := rrfScores(got)
	assert.Greater(t, scores["a"], scores["b"])
	assert.Greater(t, scores["b"], scores["c"])
}

// Documents that appear in BOTH rankings should rank
// higher than documents that appear in only one.
func TestRRF_OverlapBeatsSingleSource(t *testing.T) {
	t.Parallel()

	semantic := []string{"a", "x", "y"}
	keyword := []string{"a", "b", "c"}
	got := rrfFuse(semantic, keyword, 60)
	scores := rrfScores(got)

	// 'a' is in both lists (top of both); x/y/b/c appear
	// in only one. 'a' must rank above any of them.
	assert.Greater(t, scores["a"], scores["x"], "'a' should beat a single-source hit")
	assert.Greater(t, scores["a"], scores["b"])
	assert.Greater(t, scores["a"], scores["c"])
	assert.Greater(t, scores["a"], scores["y"])
}

// Documents that appear in NEITHER ranking must not appear
// in the fused result. Defensive: callers can pass empty
// rankings without us emitting bogus IDs.
func TestRRF_NoCrossListPollution(t *testing.T) {
	t.Parallel()

	semantic := []string{"a", "b"}
	keyword := []string{"c", "d"}
	got := rrfFuse(semantic, keyword, 60)
	ids := rrfIDs(got)

	// All four IDs should be present (two from each side).
	assert.ElementsMatch(t, []string{"a", "b", "c", "d"}, ids)
}

// RRF is deterministic — same input always yields the same
// fused ranking. Critical property: callers must not get
// different results on consecutive identical queries.
func TestRRF_Deterministic(t *testing.T) {
	t.Parallel()

	semantic := []string{"a", "b", "c", "d"}
	keyword := []string{"d", "c", "b", "a"}

	first := rrfFuse(semantic, keyword, 60)
	second := rrfFuse(semantic, keyword, 60)

	require.Len(t, first, len(second))
	for i := range first {
		assert.Equal(t, first[i].ID, second[i].ID,
			"position %d must match across runs", i)
		assert.InDelta(t, first[i].Score, second[i].Score, 1e-9)
	}
}

// The k constant only affects the absolute score scale; the
// ranking should be invariant to k. This is the property
// that lets us pick k=60 as a default without tuning.
func TestRRF_KInvariant(t *testing.T) {
	t.Parallel()

	semantic := []string{"a", "b", "c"}
	keyword := []string{"b", "a", "c"}

	at60 := rrfIDs(rrfFuse(semantic, keyword, 60))
	at1 := rrfIDs(rrfFuse(semantic, keyword, 1))
	at1000 := rrfIDs(rrfFuse(semantic, keyword, 1000))

	assert.Equal(t, at60, at1, "k must not change ranking")
	assert.Equal(t, at60, at1000)
}

// Empty rankings are tolerated (no panic, empty result).
// Hits present in ONE ranking still surface — only when
// BOTH rankings are empty does the fused result become empty.
func TestRRF_EmptyRankings(t *testing.T) {
	t.Parallel()

	assert.Empty(t, rrfFuse(nil, nil, 60))
	assert.Empty(t, rrfFuse([]string{}, []string{}, 60))
	assert.Len(t, rrfFuse([]string{"a"}, nil, 60), 1,
		"hits in one ranking must still surface")
	assert.Len(t, rrfFuse(nil, []string{"a"}, 60), 1,
		"hits in one ranking must still surface")
}

// ------------------------------------------------------------------
// Integration: SearchHybrid exercises the full semantic+keyword
// pipeline through VectorOperations. These tests use the
// real VectorDB + real SearchIndex + a stub embeddings server
// so we can assert ordering end-to-end.
// ------------------------------------------------------------------

// Hybrid search returns the union of both rankings, with
// documents that appear in BOTH ranking lists ranked
// higher than documents that appear in only one.
func TestSearchHybrid_OverlapBeatsSingleSource(t *testing.T) {
	t.Parallel()

	vo, _, _ := fixtureVO(t)
	vo.embeddings = stubEmbeddings(t)

	// Ingest three docs:
	//   docA: content matches the query by keyword AND
	//          has a distinct embedding (different position
	//          in vector space thanks to the deterministic stub).
	//   docB: matches by keyword only.
	//   docC: matches by semantic only (high similarity
	//          because its embedding is close to the query's).
	//
	// Stub embeddings:
	//   vec[0] = 1.0 always for the first input; but
	//   the query embedding is also generated by the stub,
	//   which assigns vec[i % dim] = 1.0 for the i-th input.
	//   So query embedding = [1, 0, 0, 0]; first doc's
	//   embedding = [1, 0, 0, 0] (high similarity); second
	//   doc's = [0, 1, 0, 0] (lower); third doc's = [0, 0, 1, 0]
	//   (still closer than no overlap). Real cosine will
	//   rank them in this order.
	require.NoError(t, vo.IngestDocument(context.Background(),
		testDoc(t, "docA", "kubernetes", "kubernetes ingress tls")))
	require.NoError(t, vo.IngestDocument(context.Background(),
		testDoc(t, "docB", "filler", "unrelated noise about cats")))
	require.NoError(t, vo.IngestDocument(context.Background(),
		testDoc(t, "docC", "filler", "tls handshake fails often")))

	// Query: "tls" — matches docA and docC by keyword.
	results, err := vo.SearchHybrid(context.Background(), "tls", 5, SearchFilters{}, ModeHybrid)
	require.NoError(t, err)
	require.NotEmpty(t, results)

	// docA is in BOTH rankings (semantic #1 + keyword match)
	// → it must rank above docC (keyword only).
	ids := rrfResultIDs(results)
	aIdx := indexOf(ids, "docA-c0")
	cIdx := indexOf(ids, "docC-c0")
	require.GreaterOrEqual(t, aIdx, 0, "docA must appear in results")
	require.GreaterOrEqual(t, cIdx, 0, "docC must appear in results")
	assert.Less(t, aIdx, cIdx,
		"docA (in both rankings) should rank above docC (in keyword only)")
}

// Pure semantic mode ignores the keyword index entirely;
// results must come only from the vector DB. Verified by
// indexing a chunk that's only in the keyword side — it
// must NOT appear in semantic-only results.
func TestSearchHybrid_SemanticModeIgnoresKeywordIndex(t *testing.T) {
	t.Parallel()

	vo, _, idx := fixtureVO(t)
	vo.embeddings = stubEmbeddings(t)

	require.NoError(t, vo.IngestDocument(context.Background(),
		testDoc(t, "docA", "alpha", "kubernetes")))

	// Manually add a chunk to the keyword index that the
	// vector DB does NOT have. If semantic mode leaked
	// keyword results, this would show up.
	require.NoError(t, idx.AddBatch([]chunkSummary{
		{ID: "ghost", Content: "kubernetes ghost entry", DocumentID: "ghost-doc"},
	}))

	results, err := vo.SearchHybrid(context.Background(), "kubernetes", 5, SearchFilters{}, ModeSemantic)
	require.NoError(t, err)
	for _, r := range results {
		assert.NotEqual(t, "ghost", r.ChunkID,
			"semantic mode must not return keyword-only chunks")
	}
}

// Pure keyword mode ignores the vector DB entirely; the
// results must come only from the keyword index.
func TestSearchHybrid_KeywordModeIgnoresVectorDB(t *testing.T) {
	t.Parallel()

	vo, _, idx := fixtureVO(t)
	vo.embeddings = stubEmbeddings(t)

	require.NoError(t, vo.IngestDocument(context.Background(),
		testDoc(t, "docA", "alpha", "kubernetes")))

	// Add a chunk to the keyword index that the vector DB
	// does NOT have. Keyword-only results must include it.
	require.NoError(t, idx.AddBatch([]chunkSummary{
		{ID: "keyword-only", Content: "kubernetes ghost entry", DocumentID: "ghost-doc"},
	}))

	results, err := vo.SearchHybrid(context.Background(), "kubernetes", 5, SearchFilters{}, ModeKeyword)
	require.NoError(t, err)
	require.NotEmpty(t, results)
	hasKeywordOnly := false
	for _, r := range results {
		if r.ChunkID == "keyword-only" {
			hasKeywordOnly = true
		}
	}
	assert.True(t, hasKeywordOnly,
		"keyword mode must return keyword-only chunks")
}

// Filters are pre-applied to BOTH rankings before fusion:
// a chunk that fails the document_id filter must never
// appear in hybrid results.
func TestSearchHybrid_FilterPreappliedToBothRankings(t *testing.T) {
	t.Parallel()

	vo, _, _ := fixtureVO(t)
	vo.embeddings = stubEmbeddings(t)

	require.NoError(t, vo.IngestDocument(context.Background(),
		testDoc(t, "doc-a", "alpha", "kubernetes ingress")))
	require.NoError(t, vo.IngestDocument(context.Background(),
		testDoc(t, "doc-b", "alpha", "kubernetes networking")))

	results, err := vo.SearchHybrid(context.Background(), "kubernetes", 5,
		SearchFilters{DocumentID: "doc-a"}, ModeHybrid)
	require.NoError(t, err)
	require.NotEmpty(t, results)
	for _, r := range results {
		assert.Equal(t, "doc-a", r.DocumentID,
			"hybrid results must respect document_id filter")
	}
}

// Hybrid search without a keyword index wired gracefully
// degrades to pure semantic search.
func TestSearchHybrid_NoKeywordIndexIsSemanticOnly(t *testing.T) {
	t.Parallel()

	db, err := NewVectorDB("test-"+t.Name(), 4, "")
	require.NoError(t, err)
	t.Cleanup(func() { _ = db.Close() })

	vo := NewVectorOperations(db, stubEmbeddings(t))
	// No SetSearchIndex — keyword side is nil.

	require.NoError(t, vo.IngestDocument(context.Background(),
		testDoc(t, "docA", "alpha", "kubernetes")))

	results, err := vo.SearchHybrid(context.Background(), "kubernetes", 5,
		SearchFilters{}, ModeHybrid)
	require.NoError(t, err)
	require.NotEmpty(t, results, "hybrid without keyword index must still return semantic results")
}

// limit caps the returned slice to the requested size even
// when both rankings produce more candidates than limit.
func TestSearchHybrid_RespectsLimit(t *testing.T) {
	t.Parallel()

	vo, _, _ := fixtureVO(t)
	vo.embeddings = stubEmbeddings(t)

	for i := range 10 {
		id := "doc" + string(rune('A'+i))
		require.NoError(t, vo.IngestDocument(context.Background(),
			testDoc(t, id, "alpha", "kubernetes notes "+string(rune('A'+i)))))
	}

	results, err := vo.SearchHybrid(context.Background(), "kubernetes", 3,
		SearchFilters{}, ModeHybrid)
	require.NoError(t, err)
	assert.LessOrEqual(t, len(results), 3)
}

// ------------------------------------------------------------------
// helpers
// ------------------------------------------------------------------

// rrfScores flattens a fused ranking into a map of ID → score.
func rrfScores(fused []rrfItem) map[string]float64 {
	out := make(map[string]float64, len(fused))
	for _, it := range fused {
		out[it.ID] = it.Score
	}
	return out
}

// rrfIDs extracts just the IDs in ranking order.
func rrfIDs(fused []rrfItem) []string {
	out := make([]string, 0, len(fused))
	for _, it := range fused {
		out = append(out, it.ID)
	}
	return out
}

// rrfResultIDs extracts the chunk IDs from a slice of
// SearchResults.
func rrfResultIDs(results []searchHybridResult) []string {
	out := make([]string, 0, len(results))
	for _, r := range results {
		out = append(out, r.ChunkID)
	}
	sort.Strings(out)
	return out
}

// indexOf returns the index of needle in haystack, or -1.
func indexOf(haystack []string, needle string) int {
	for i, s := range haystack {
		if s == needle {
			return i
		}
	}
	return -1
}
